# Generated by Django 3.1.3 on 2020-11-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201108_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
